name: New Instrument
description: Add new instrument to NCAS instrument list
title: New instrument request
labels: ["new-instrument"]
assignees:
  - joshua-hampton, gap736uk
body:
  - type: markdown
    attributes:
      value: |
        Please fill in the following to provide information about the new instrument.
  - type: input
    id: manufacturer
    attributes:
      label: Instrument Manufacturer
      description: Name of the company that made the instrument.
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Instrument Model
      description: Model name or number of the instrument.
    validations:
      required: true
  - type: input
    id: serial
    attributes:
      label: Instrument Serial Number
      description: Serial number of the instrument.
    validations:
      required: true
  - type: input
    id: scientist-name
    attributes:
      label: Instrument Scientist Name
      description: Name of the scientist resposible for the instrument.
    validations:
      required: true
  - type: input
    id: scientist-orcid
    attributes:
      label: Instrument Scientist ORCID
      description: ORCID of the instrument scientist.
    validations:
      required: true
  - type: dropdown
    id: instrument-owner
    attributes:
      label: Instrument Owner (and ROR ID)
      description: Legal owner of the instrument.
      multiple: false
      options:
        - National Centre for Atmospheric Science (https://ror.org/01wwwe276)
        - Science and Technology Facilities Council (https://ror.org/057g20z61)
        - University of East Anglia (https://ror.org/026k5mg93)
        - University of Leeds (https://ror.org/024mrxd33)
        - University of Manchester (https://ror.org/027m9bs27)
        - University of York (https://ror.org/04m01e293)
        - Other
    validations:
      required: true
  - type: input
    id: instrument-owner-other
    attributes:
      label: If "Other" selected above, please type the owner and ROR ID (if known) below.
    validations:
      required: false
  - type: dropdown
    id: location
    attributes:
      label: NCAS Observatory
      description: Observatory at which instrument will be primarily located. For mobile instruments, select "mobile"
      multiple: false
      options:
        - BTTAO
        - CAO
        - CDAO
        - CVAO
        - IAO
        - WAO
        - mobile
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Instrument description
      description: Please provide a brief description of the instrument, including how it works and what it measures (no more than a few sentances).
    validations:
      required: true
